#!/bin/bash

echo "Running script"
#d=1262304000
d=`date -jf"%Y-%m-%d" "2010-01-01" +%s`

while true; do 
    p=`date -jf"%s" $d +"%Y-%m-%d"`
    #echo $p
    `node client.js "$p" >/dev/null 2>&1`
    d=$(($d+7*24*60*60))
    if [ $d -gt `date -jf"%Y-%m-%d" "2010-05-01" +%s` ]; # `date +%s`
        then
            exit 0
    fi
    sleep 1 
done
